[package]
name = "selfplay"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
engine = { path = "../../engine" }
sdk = { path = "../../sdk" }
move_gen = { path = "../../move-gen" }
